EXTERN(vector_table)
ENTRY(reset_handler)
MEMORY
{
  ram (rwx) : ORIGIN = 0x20000000, LENGTH = 20K
  rom (rx)  : ORIGIN = 0x08000000, LENGTH = 64K
}
SECTIONS
{
  .text : {
    *(.vectors)
    *(.text*)
    . = ALIGN(4);
    *(.rodata*)
    . = ALIGN(4);
  } >rom
  . = ALIGN(4);
  _etext = .;
  .data : {
    _data = .;
    *(.data*)
    . = ALIGN(4);
    _edata = .;
  } >ram AT >rom
  _data_loadaddr = LOADADDR(.data);
  .bss : {
    _bss = .;
    *(.bss*)
    *(COMMON)
    . = ALIGN(4);
    _ebss = .;
  } >ram
  . = ALIGN(4);
  end = .;
}
PROVIDE(_stack = ORIGIN(ram) + LENGTH(ram));
